// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// retrofit_step3_alpha_numerator
NumericVector retrofit_step3_alpha_numerator(NumericVector W_gk, NumericVector TH_k, NumericVector H_ks, float lambda);
RcppExport SEXP _retrofit_retrofit_step3_alpha_numerator(SEXP W_gkSEXP, SEXP TH_kSEXP, SEXP H_ksSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type W_gk(W_gkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TH_k(TH_kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type H_ks(H_ksSEXP);
    Rcpp::traits::input_parameter< float >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(retrofit_step3_alpha_numerator(W_gk, TH_k, H_ks, lambda));
    return rcpp_result_gen;
END_RCPP
}
// retrofit_step3_alpha_denominator
NumericVector retrofit_step3_alpha_denominator(NumericVector phi_a_gks);
RcppExport SEXP _retrofit_retrofit_step3_alpha_denominator(SEXP phi_a_gksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type phi_a_gks(phi_a_gksSEXP);
    rcpp_result_gen = Rcpp::wrap(retrofit_step3_alpha_denominator(phi_a_gks));
    return rcpp_result_gen;
END_RCPP
}
// retrofit_step3_alpha
NumericVector retrofit_step3_alpha(NumericVector W_gk, NumericVector TH_k, NumericVector H_ks, float lambda);
RcppExport SEXP _retrofit_retrofit_step3_alpha(SEXP W_gkSEXP, SEXP TH_kSEXP, SEXP H_ksSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type W_gk(W_gkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TH_k(TH_kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type H_ks(H_ksSEXP);
    Rcpp::traits::input_parameter< float >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(retrofit_step3_alpha(W_gk, TH_k, H_ks, lambda));
    return rcpp_result_gen;
END_RCPP
}
// retrofit_step3_beta
NumericVector retrofit_step3_beta(NumericVector W_gk, NumericVector TH_k, float lambda);
RcppExport SEXP _retrofit_retrofit_step3_beta(SEXP W_gkSEXP, SEXP TH_kSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type W_gk(W_gkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TH_k(TH_kSEXP);
    Rcpp::traits::input_parameter< float >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(retrofit_step3_beta(W_gk, TH_k, lambda));
    return rcpp_result_gen;
END_RCPP
}
// retrofit_step4_alpha_w
NumericVector retrofit_step4_alpha_w(NumericVector x_gs, NumericVector phi_a_gks, NumericVector phi_b_gk, float alpha_w_0);
RcppExport SEXP _retrofit_retrofit_step4_alpha_w(SEXP x_gsSEXP, SEXP phi_a_gksSEXP, SEXP phi_b_gkSEXP, SEXP alpha_w_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_gs(x_gsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_a_gks(phi_a_gksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_b_gk(phi_b_gkSEXP);
    Rcpp::traits::input_parameter< float >::type alpha_w_0(alpha_w_0SEXP);
    rcpp_result_gen = Rcpp::wrap(retrofit_step4_alpha_w(x_gs, phi_a_gks, phi_b_gk, alpha_w_0));
    return rcpp_result_gen;
END_RCPP
}
// retrofit_step4_alpha_h
NumericVector retrofit_step4_alpha_h(NumericVector x_gs, NumericVector phi_a_gks, float alpha_h_0);
RcppExport SEXP _retrofit_retrofit_step4_alpha_h(SEXP x_gsSEXP, SEXP phi_a_gksSEXP, SEXP alpha_h_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_gs(x_gsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_a_gks(phi_a_gksSEXP);
    Rcpp::traits::input_parameter< float >::type alpha_h_0(alpha_h_0SEXP);
    rcpp_result_gen = Rcpp::wrap(retrofit_step4_alpha_h(x_gs, phi_a_gks, alpha_h_0));
    return rcpp_result_gen;
END_RCPP
}
// retrofit_step4_alpha_th
NumericVector retrofit_step4_alpha_th(NumericVector x_gs, NumericVector phi_a_gks, NumericVector phi_b_gk, float alpha_th_0);
RcppExport SEXP _retrofit_retrofit_step4_alpha_th(SEXP x_gsSEXP, SEXP phi_a_gksSEXP, SEXP phi_b_gkSEXP, SEXP alpha_th_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_gs(x_gsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_a_gks(phi_a_gksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_b_gk(phi_b_gkSEXP);
    Rcpp::traits::input_parameter< float >::type alpha_th_0(alpha_th_0SEXP);
    rcpp_result_gen = Rcpp::wrap(retrofit_step4_alpha_th(x_gs, phi_a_gks, phi_b_gk, alpha_th_0));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_second_dim_sum
NumericVector rcpp_second_dim_sum(NumericVector v);
RcppExport SEXP _retrofit_rcpp_second_dim_sum(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_second_dim_sum(v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_retrofit_retrofit_step3_alpha_numerator", (DL_FUNC) &_retrofit_retrofit_step3_alpha_numerator, 4},
    {"_retrofit_retrofit_step3_alpha_denominator", (DL_FUNC) &_retrofit_retrofit_step3_alpha_denominator, 1},
    {"_retrofit_retrofit_step3_alpha", (DL_FUNC) &_retrofit_retrofit_step3_alpha, 4},
    {"_retrofit_retrofit_step3_beta", (DL_FUNC) &_retrofit_retrofit_step3_beta, 3},
    {"_retrofit_retrofit_step4_alpha_w", (DL_FUNC) &_retrofit_retrofit_step4_alpha_w, 4},
    {"_retrofit_retrofit_step4_alpha_h", (DL_FUNC) &_retrofit_retrofit_step4_alpha_h, 3},
    {"_retrofit_retrofit_step4_alpha_th", (DL_FUNC) &_retrofit_retrofit_step4_alpha_th, 4},
    {"_retrofit_rcpp_second_dim_sum", (DL_FUNC) &_retrofit_rcpp_second_dim_sum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_retrofit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
