// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// alpha_denominator
NumericVector alpha_denominator(NumericVector phi_a_gks);
RcppExport SEXP _retrofit_alpha_denominator(SEXP phi_a_gksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type phi_a_gks(phi_a_gksSEXP);
    rcpp_result_gen = Rcpp::wrap(alpha_denominator(phi_a_gks));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_second_dim_sum
NumericVector rcpp_second_dim_sum(NumericVector v);
RcppExport SEXP _retrofit_rcpp_second_dim_sum(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_second_dim_sum(v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_retrofit_alpha_denominator", (DL_FUNC) &_retrofit_alpha_denominator, 1},
    {"_retrofit_rcpp_second_dim_sum", (DL_FUNC) &_retrofit_rcpp_second_dim_sum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_retrofit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
