# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decompose_compute_error_two_norm <- function(original, inferred) {
    .Call(`_retrofit_decompose_compute_error_two_norm`, original, inferred)
}

decompose_compute_error_mat_norm <- function(original, inferred) {
    .Call(`_retrofit_decompose_compute_error_mat_norm`, original, inferred)
}

decompose_compute_and_update_error_two_norm <- function(original, inferred) {
    .Call(`_retrofit_decompose_compute_and_update_error_two_norm`, original, inferred)
}

decompose_compute_and_update_error_mat_norm <- function(original, inferred) {
    .Call(`_retrofit_decompose_compute_and_update_error_mat_norm`, original, inferred)
}

decompose_step2 <- function(shapes, rates, out) {
    invisible(.Call(`_retrofit_decompose_step2`, shapes, rates, out))
}

decompose_step3_alpha <- function(distributions, lambda, dim, phi_a_gks) {
    invisible(.Call(`_retrofit_decompose_step3_alpha`, distributions, lambda, dim, phi_a_gks))
}

decompose_step3_beta <- function(distributions, lambda, dim, phi_b_gk) {
    invisible(.Call(`_retrofit_decompose_step3_beta`, distributions, lambda, dim, phi_b_gk))
}

decompose_step4_alpha <- function(x_gs, probabilities, alpha_w_0, alpha_h_0, alpha_th_0, dim) {
    .Call(`_retrofit_decompose_step4_alpha`, x_gs, probabilities, alpha_w_0, alpha_h_0, alpha_th_0, dim)
}

decompose_step4_beta <- function(distributions, beta_w_0, beta_h_0, beta_th_0, lambda, dim) {
    .Call(`_retrofit_decompose_step4_beta`, distributions, beta_w_0, beta_h_0, beta_th_0, lambda, dim)
}

decompose_step5 <- function(main, asterisk, rho) {
    invisible(.Call(`_retrofit_decompose_step5`, main, asterisk, rho))
}

