# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

retrofit_decomposition_step2 <- function(shapes, rates, out) {
    invisible(.Call(`_retrofit_retrofit_decomposition_step2`, shapes, rates, out))
}

retrofit_decomposition_step3_alpha <- function(distributions, lambda, dim, phi_a_gks) {
    invisible(.Call(`_retrofit_retrofit_decomposition_step3_alpha`, distributions, lambda, dim, phi_a_gks))
}

retrofit_decomposition_step3_beta <- function(distributions, lambda, dim, phi_b_gk) {
    invisible(.Call(`_retrofit_retrofit_decomposition_step3_beta`, distributions, lambda, dim, phi_b_gk))
}

retrofit_step4_alpha_calculation <- function(x_gs, phi_a_gks, phi_b_gk, alpha_w_0, alpha_h_0, alpha_th_0, dim) {
    .Call(`_retrofit_retrofit_step4_alpha_calculation`, x_gs, phi_a_gks, phi_b_gk, alpha_w_0, alpha_h_0, alpha_th_0, dim)
}

retrofit_step4_beta_calculation <- function(W_gk, H_ks, TH_k, beta_w_0, beta_h_0, beta_th_0, lambda, dim) {
    .Call(`_retrofit_retrofit_step4_beta_calculation`, W_gk, H_ks, TH_k, beta_w_0, beta_h_0, beta_th_0, lambda, dim)
}

retrofit_step5_parameter_estimation <- function(original, update, rho) {
    .Call(`_retrofit_retrofit_step5_parameter_estimation`, original, update, rho)
}

rcpp_second_dim_sum <- function(v) {
    .Call(`_retrofit_rcpp_second_dim_sum`, v)
}

